name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # 每天 UTC 时间 0点 运行一次
  workflow_dispatch:    # 允许用户手动点击按钮触发

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }} # 只有当仓库是 Fork 的时候才运行，避免你自己运行自己

    steps:
      # 步骤 1: 检出代码
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          # 【同步工作流需要PERSONAL_ACCESS_TOKEN】在这里就指定使用你的 PAT，覆盖默认的 GITHUB_TOKEN
          token: ${{ secrets.ACTION_TOKEN }} 
          persist-credentials: true

      # 步骤 2: 同步上游
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: ieax/renewhelper # 你的上游仓库地址 (用户名/仓库名)
          upstream_sync_branch: main           # 你更新的分支
          target_sync_branch: main             # Fork 仓库要更新的分支
          target_repo_token: ${{ secrets.ACTION_TOKEN }} # 使用你的 PAT，覆盖默认的 GITHUB_TOKEN
          test_mode: false

      # 步骤 3: 检查是否有新提交（可选，用于显示日志）
      - name: Check for new commits
        if: steps.sync.outputs.has_new_commits == 'true'
        run: echo "New commits were found to sync."

      - name: No new commits
        if: steps.sync.outputs.has_new_commits == 'false'
        run: echo "There were no new commits."
            
      - name: Show value of 'has_new_commits'
        run: echo ${{ steps.sync.outputs.has_new_commits }}
